### ISSUE TITLE
Theme: i18n page templates aren't being generated.

### ISSUE THREAD

**Issue by EricDunsworth** [wet-boew/theme-ogpl#137]
While revising #130, I noticed that [this theme's index page](http://wet-boew.github.io/themes-dist/theme-ogpl/index-en.html) links out to non-existent i18n page templates. All link destinations are formatted properly. The problem is that this theme isn't setup to generate i18n page templates at all. It also lacks i18n variables for its custom strings.

From what I can tell, the OGPL theme has always only contained French and English page templates. In August 2014, #77 added i18n sections/links into the theme's index page. It's been like that since v4.0.5+.

@pjackson28 Was the OGPL theme ever meant to have i18n page templates? Or were #77's i18n additions just an oversight?

**Comment by pjackson28** [comment]
@EricDunsworth At the time the intention was to include more languages since OGPL was originally a joint initiative between the US and India that was expanding to other countries so would include language support for those countries. I don't think OGPL is around any more as the related sites seem to be shut down and the OGPL GitHub presence seems to have been inactive for a few years. Might be worth considering sunsetting this theme or changing and renaming it into another example theme.

**Comment by EricDunsworth** [comment]
@pjackson28 Thanks for clearing that up :)!

I'll open up a separate issue about dropping this theme soon. I was actually starting to prep one up before I saw your comment.
